---
jobs: ~
version: 2
workflows:
  version: 2
  build: ~
  build-and-deploy-on-hold: ~
  deploy-development: ~
  deploy-prod: ~
  test: ~
    docker: ~
    jobs: ~
    steps:
  - checkout
    working_directory: ~/challenge-backend
"      - hold":
  requires:
    - test
  type: approval
"      - run": "yarn install"
"      - save_cache":
  key: 'v1-dependencies-{{ checksum "package.json" }}'
  paths:
    - node_modules
      - build: ~
      - deploy-development: ~
      - deploy-prod: ~
'      - image: "circleci/node': 8.9.4"
      - restore_cache: ~
      - run: ~
      - test: ~
          command: "git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master\n"
          filters:
  branches:
    only:
      - production
          keys:
  - 'v1-dependencies-{{ checksum "package.json" }}'
  - v1-dependencies-
          name: Deploy Master to Heroku
          requires:
  - build
  - test
  - hold
