version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.x
    working_directory: ~/challenge-backend
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  test:
    docker:
      - image: circleci/node:10.x
    working_directory: ~/challenge-backend
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn test

  # Deploying

  deploy-development:
    docker:
      - image: circleci/node:10.x
    working_directory: ~/challenge-backend
    steps:
      - checkout
      - command: # shell

  deploy-prod:
    docker:
      - image: circleci/node:10.x
    working_directory: ~/challenge-backend
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2.1
  build-and-deploy-on-hold:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - develop
      - test:
          requires:
            - build

      - hold:
          type: approval
          requires:
            - test

      - deploy-development:
          requires:
            - test
            - build
          filters:
            branches:
              only: develop

      - deploy-prod:
          requires:
            - build
            - test
            - hold
          filters:
            branches:
              only: master