version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.18.1

    working_directory: ~/challenge-backend

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  test:
    docker:
      - image: circleci/node:10.18.1

    working_directory: ~/challenge-backend

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn test

  # Deploying
  deploy-development:
    docker:
      - image: circleci/node:10.18.1
    working_directory: ~/challenge-backend

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

  deploy-prod:
    docker:
      - image: circleci/node:10.18.1
    working_directory: ~/challenge-backend

    steps:
      - checkout

      - run:
          name: Deploy from Production branch to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git production

workflows:
  version: 2
  build-and-deploy-on-hold:
    jobs:
      - build:
          filters:
            branches:
              only:
                - production
                - develop

      - test:
          requires:
            - build

      - deploy-development:
          requires:
            - build
            - test
          filters:
            branches:
              only: develop

      - deploy-prod:
          requires:
            - build
            - test
          filters:
            branches:
              only: production
